=== simonharvan/sipvs/car-rent.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="car-rent">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="orderperson">
          <xs:complexType>
            <xs:element name="person">
              <xs:complexType>
                <xs:sequence>
                  <xs:element type="xs:string" name="name"/>
                  <xs:element type="xs:string" name="date-of-birth"/>
                  <xs:element type="xs:string" name="id"/>
                  <xs:element type="xs:string" name="email"/>
                  <xs:element type="xs:string" name="phone-number"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:complexType>
        </xs:element>
        <xs:element name="passengers">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="person" maxOccurs="4" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="date-of-birth"/>
                    <xs:element type="xs:string" name="id"/>
                    <xs:element type="xs:string" name="email"/>
                    <xs:element type="xs:string" name="phone-number"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="car">
          <xs:complexType>
            <xs:element type="xs:string" name="brand"/>
            <xs:element type="xs:string" name="type"/>
            <xs:element type="xs:short" name="year"/>
            <xs:element type="xs:string" name="color"/>
            <xs:element type="xs:string" name="license-plate"/>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:float" name="price"/>
      </xs:sequence>
      <xs:attribute type="xs:int" name="orderid"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== simonharvan/sipvs/car-rent.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="car-rent.xsl"?>
<car-rent orderid="889923"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="car-rent.xsd">
    <orderperson>
        <person>
            <name>John Smith</name>
            <date-of-birth>09-12-1993</date-of-birth>
            <id>EC123056</id>
            <email>john@smith.com</email>
            <phone-number>+421911099339</phone-number>
        </person>
    </orderperson>
    <passengers>
        <person>
            <name>John Smith</name>
            <date-of-birth>09-12-1993</date-of-birth>
            <id>EC123056</id>
            <email>john@smith.com</email>
            <phone-number>+421911099339</phone-number>
        </person>
        <person>
            <name>John Smith</name>
            <date-of-birth>09-12-1993</date-of-birth>
            <id>EC123056</id>
            <email>john@smith.com</email>
            <phone-number>+421911099339</phone-number>
        </person>
        <person>
            <name>John Smith</name>
            <date-of-birth>09-12-1993</date-of-birth>
            <id>EC123056</id>
            <email>john@smith.com</email>
            <phone-number>+421911099339</phone-number>
        </person>
    </passengers>
    <car>
        <brand>Skoda</brand>
        <type>Octavia</type>
        <model>hatchback</model>
        <engine>diesel</engine>
        <color>Gray</color>
        <year>2005</year>
        <number_of_days>10</number_of_days>
        <price>10.56</price>
    </car>
</car-rent>
